In [10]:
from mmseg.apis import MMSegInferencer

from mmseg.registry import DATASETS
from mmseg.datasets import BaseSegDataset

old_classes = ['Outside billboards', 'Billboard', 'Field player', 'Goalkeeper', 'Referee', 'Assistant referee', 'Other human', 'Ball', 'Goal post', 'Goal net', 'Net post', 'Cross-bar', 'Corner flag', 'Assistant flag', 'Microphone', 'Camera', 'Other object', 'Don\'t care']
old_palette = [[0, 0, 0], [255, 255, 255], [255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 0, 0], [0, 128, 0], [0, 0, 128], [64, 64, 64], [128, 128, 0], [128, 0, 128], [0, 128, 128], [255, 128, 0], [192, 192, 192], [128, 128, 128]]

new_classes = ['Outside billboards', 'Billboard', 'Goal net']
new_palette = [old_palette[old_classes.index(c)] for c in new_classes]

# Check if the dataset SoccerNet is already registered
if 'SoccerNet' not in DATASETS:
	@DATASETS.register_module()
	class SoccerNet(BaseSegDataset):
		METAINFO = dict(classes = new_classes, palette = new_palette)
		def __init__(self, **kwargs):
			super().__init__(img_suffix='.png', seg_map_suffix='.png', **kwargs)

In [11]:
from mmengine.config import Config

In [12]:
cfg = Config.fromfile('./models/mask2former/mask2former_swin-t_1xb2-90k_soccernet.py')
# cfg.test_dataloader.dataset.pipeline = cfg.tta_pipeline
# cfg.tta_model.module = cfg.model
# cfg.model = cfg.tta_model

In [13]:
inferencer = MMSegInferencer(model=cfg, weights='best_mIoU_iter_46200.pth', classes=new_classes, palette=new_palette)

Loads checkpoint by local backend from path: best_mIoU_iter_46200.pth


In [14]:
img_list = ["Stadium_4_Match_2_in_1fps_6662", "Stadium_4_Match_2_in022", "Stadium_4_Match_2_in_1fps_6615", "Stadium_4_Match_2_in_1fps_6451", "Stadium_4_Match_2_in_1fps_6497", "Stadium_4_Match_2_in_1fps_5734", "Stadium_4_Match_2_in_1fps_5374", "Stadium_4_Match_2_in_1fps_5363", "Stadium_4_Match_2_in_1fps_5353", "Stadium_4_Match_2_in_1fps_5356", "Stadium_4_Match_2_in_1fps_5000", "Stadium_4_Match_2_in_1fps_4524", "Stadium_4_Match_2_in_1fps_4289", "Stadium_4_Match_2_in_1fps_2717", "Stadium_4_Match_2_in_1fps_2061", "Stadium_4_Match_2_in_1fps_2058"]

In [15]:
# For each item in the list, add 'Dataset/Images/' and '.png' to get the path to the image
img_list = ['Dataset/Images/' + i + '.png' for i in img_list]

In [16]:
# Load all file names from ./test/SNMOT-116/img1/

import os

# Get all file names from ./test/SNMOT-116/img1/
path = './soccernet-tracking/tracking/test/SNMOT-116/img1/'
files = os.listdir(path)
files.sort()
files

['000001.jpg',
 '000002.jpg',
 '000003.jpg',
 '000004.jpg',
 '000005.jpg',
 '000006.jpg',
 '000007.jpg',
 '000008.jpg',
 '000009.jpg',
 '000010.jpg',
 '000011.jpg',
 '000012.jpg',
 '000013.jpg',
 '000014.jpg',
 '000015.jpg',
 '000016.jpg',
 '000017.jpg',
 '000018.jpg',
 '000019.jpg',
 '000020.jpg',
 '000021.jpg',
 '000022.jpg',
 '000023.jpg',
 '000024.jpg',
 '000025.jpg',
 '000026.jpg',
 '000027.jpg',
 '000028.jpg',
 '000029.jpg',
 '000030.jpg',
 '000031.jpg',
 '000032.jpg',
 '000033.jpg',
 '000034.jpg',
 '000035.jpg',
 '000036.jpg',
 '000037.jpg',
 '000038.jpg',
 '000039.jpg',
 '000040.jpg',
 '000041.jpg',
 '000042.jpg',
 '000043.jpg',
 '000044.jpg',
 '000045.jpg',
 '000046.jpg',
 '000047.jpg',
 '000048.jpg',
 '000049.jpg',
 '000050.jpg',
 '000051.jpg',
 '000052.jpg',
 '000053.jpg',
 '000054.jpg',
 '000055.jpg',
 '000056.jpg',
 '000057.jpg',
 '000058.jpg',
 '000059.jpg',
 '000060.jpg',
 '000061.jpg',
 '000062.jpg',
 '000063.jpg',
 '000064.jpg',
 '000065.jpg',
 '000066.jpg',
 '000067.j

In [17]:
img_list = [path + i for i in files]
img_list

['./soccernet-tracking/tracking/test/SNMOT-116/img1/000001.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000002.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000003.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000004.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000005.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000006.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000007.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000008.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000009.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000010.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000011.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000012.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000013.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000014.jpg',
 './soccernet-tracking/tracking/test/SNMOT-116/img1/000015.jpg',
 './soccernet-tracking/tr

In [44]:
# If out_dir is '', it won't save the results
results = inferencer(img_list[:5])

In [45]:
results['predictions']

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
   

In [47]:
import torch
import numpy as np

In [51]:
tmp = torch.tensor(np.array(results['predictions']), device='cuda')

In [52]:
torch.tensor(np.array(results['predictions']), device='cuda')

from timeit import timeit

timeit('torch.tensor(np.array(results[\'predictions\']), device=\'cuda\')', globals=globals(), number=1)

0.032751662000009674